In [2]:
import pandas as pd

## 一、csv文件

### （一）读

In [24]:
# 这里采用双斜杠\\原因是由于读取文件和python文件没有在同一个文件夹里，导致报错FileNotFoundError，需要使用绝对路径才可以
df_csv = pd.read_csv('.\\data_for_book\\chapter_06\\read_csv.csv')  
df_csv.head()
# 更多详细参数请参考官方文档或者《用python进行数据分析p170》

,贷款金额,贷款期限,利率,每月还款金额,贷款等级,工作年限,房屋所有权,年收入,收入是否由LC验证,target,贷款目的,月负债比,过去两年借款人逾期30天以上的数字,过去6个月内被查询次数,摧毁公共记录的数量,额度循环使用率,总贷款笔数,拖欠的逾期款项,留置税数量
0,18000.0,1,7.99,563.98,1,2.0,2,60000.0,3,0,debt_consolidation,30.76,0.0,0,0.0,17.8,22.0,0.0,0.0
1,13000.0,1,5.32,391.50,1,10.0,2,101800.0,3,0,credit_card,18.91,0.0,0,3.0,57.5,21.0,0.0,0.0
2,5000.0,1,10.49,162.49,2,10.0,3,75000.0,3,0,other,11.01,0.0,1,1.0,47.3,9.0,0.0,0.0
3,11100.0,1,5.32,334.28,1,3.0,3,60000.0,3,0,credit_card,18.91,0.0,0,0.0,34.4,23.0,0.0,0.0
4,25000.0,2,28.69,788.84,6,10.0,3,83807.4,1,0,debt_consolidation,13.17,0.0,0,0.0,38.6,25.0,0.0,0.0

In [25]:
# 不推荐
df_csv = pd.read_table('.\\data_for_book\\chapter_06\\read_csv.csv', sep=',')
df_csv.head()

D:\software\Anaconda\lib\site-packages\ipykernel_launcher.py:2: FutureWarning: read_table is deprecated, use read_csv instead.

,贷款金额,贷款期限,利率,每月还款金额,贷款等级,工作年限,房屋所有权,年收入,收入是否由LC验证,target,贷款目的,月负债比,过去两年借款人逾期30天以上的数字,过去6个月内被查询次数,摧毁公共记录的数量,额度循环使用率,总贷款笔数,拖欠的逾期款项,留置税数量
0,18000.0,1,7.99,563.98,1,2.0,2,60000.0,3,0,debt_consolidation,30.76,0.0,0,0.0,17.8,22.0,0.0,0.0
1,13000.0,1,5.32,391.50,1,10.0,2,101800.0,3,0,credit_card,18.91,0.0,0,3.0,57.5,21.0,0.0,0.0
2,5000.0,1,10.49,162.49,2,10.0,3,75000.0,3,0,other,11.01,0.0,1,1.0,47.3,9.0,0.0,0.0
3,11100.0,1,5.32,334.28,1,3.0,3,60000.0,3,0,credit_card,18.91,0.0,0,0.0,34.4,23.0,0.0,0.0
4,25000.0,2,28.69,788.84,6,10.0,3,83807.4,1,0,debt_consolidation,13.17,0.0,0,0.0,38.6,25.0,0.0,0.0

### （二）写

In [26]:
df_csv = pd.read_csv('.\\data_for_book\\chapter_06\\read_csv.csv')  
df_csv.to_csv('.\\data_for_book\\chapter_06\\to_csv.csv', encoding='gbk')

## 二、Excel文件

### （一）读

In [29]:
df_excel = pd.read_excel('.\\data_for_book\\chapter_06\\read_excel.xlsx', sheet_name='Sheet1', encoding='gbk')
df_excel.head()

,Unnamed: 0,贷款金额,贷款期限,利率,每月还款金额,贷款等级,工作年限,房屋所有权,年收入,收入是否由LC验证,target,贷款目的,月负债比,过去两年借款人逾期30天以上的数字,过去6个月内被查询次数,摧毁公共记录的数量,额度循环使用率,总贷款笔数,拖欠的逾期款项,留置税数量
0,0,18000,1,7.99,563.98,1,2,2,60000.0,3,0,debt_consolidation,30.76,0,0,0,17.8,22,0,0
1,1,13000,1,5.32,391.50,1,10,2,101800.0,3,0,credit_card,18.91,0,0,3,57.5,21,0,0
2,2,5000,1,10.49,162.49,2,10,3,75000.0,3,0,other,11.01,0,1,1,47.3,9,0,0
3,3,11100,1,5.32,334.28,1,3,3,60000.0,3,0,credit_card,18.91,0,0,0,34.4,23,0,0
4,4,25000,2,28.69,788.84,6,10,3,83807.4,1,0,debt_consolidation,13.17,0,0,0,38.6,25,0,0

### （二）写

In [30]:
df_csv = pd.read_csv('.\\data_for_book\\chapter_06\\read_csv.csv')  
df_csv.to_excel('.\\data_for_book\\chapter_06\\to_excel.xlsx', encoding='gbk', sheet_name='to_excel')

## 三、JSON文件

### （一）读

In [41]:
df_json = pd.read_json('.\\data_for_book\\chapter_06\\read_json.json')
df_json.head()

,贷款金额,贷款期限,利率,每月还款金额,贷款等级,工作年限,房屋所有权,年收入,收入是否由LC验证,target,贷款目的,月负债比,过去两年借款人逾期30天以上的数字,过去6个月内被查询次数,摧毁公共记录的数量,额度循环使用率,总贷款笔数,拖欠的逾期款项,留置税数量
0,18000,1,7.99,563.98,1,2,2,60000.0,3,0,debt_consolidation,30.76,0,0,0,17.8,22,0,0
1,13000,1,5.32,391.50,1,10,2,101800.0,3,0,credit_card,18.91,0,0,3,57.5,21,0,0
10,39000,1,15.99,1370.94,3,10,2,78000.0,1,0,debt_consolidation,33.14,0,0,0,52.3,29,0,0
100,6400,1,11.39,210.72,2,3,2,100000.0,1,0,credit_card,9.38,1,3,0,30.9,30,0,0
1000,3000,1,13.49,101.80,3,8,2,80000.0,1,0,major_purchase,3.74,0,0,0,88.0,13,0,0

### （二）写

In [46]:
df_csv.to_json('.\\data_for_book\\chapter_06\\to_json.json')

## 四、html文件

### （一）读

In [61]:
df_html = pd.read_html('.\\data_for_book\\chapter_06\\read_html.html', encoding='gbk')
df_html

[        Unnamed: 0     贷款金额  贷款期限     利率   每月还款金额  贷款等级  工作年限  房屋所有权  \
 0                0  18000.0     1   7.99   563.98     1   2.0      2
 1                1  13000.0     1   5.32   391.50     1  10.0      2
 2                2   5000.0     1  10.49   162.49     2  10.0      3
 3                3  11100.0     1   5.32   334.28     1   3.0      3
 4                4  25000.0     2  28.69   788.84     6  10.0      3
 5                5  25900.0     2  25.49   767.66     5  10.0      2
 6                6   5000.0     1  11.44   164.74     2  10.0      3
 7                7   6000.0     1   7.49   186.61     1   5.0      3
 8                8  21500.0     1  11.39   707.86     2  10.0      2
 9                9  10000.0     1  11.39   329.24     2   1.0      2
 10              10  39000.0     1  15.99  1370.94     3  10.0      2
 11              11   8000.0     1   7.99   250.66     1  10.0      2
 12              12  20000.0     1  16.99   712.96     4  10.0      2
 13              13  19200.0     1  13.99   656.12     3  10.0      2
 14              14  14400.0     2   7.99   291.92     1   9.0      2
 15              15   3600.0     1  11.39   118.53     2  10.0      3
 16              16   7000.0     1   5.32   210.81     1   2.0      3
 17              17   4500.0     1  12.74   151.06     3   6.0      3
 18              18  10000.0     1   5.32   301.15     1  10.0      3
 19              19  13400.0     1  13.49   454.67     3   5.0      2
 20              20  12000.0     1  16.99   427.78     4  10.0      3
 21              21   9300.0     1   8.24   292.46     2   9.0      2
 22              22  15000.0     1  19.99   557.38     4   1.0      3
 23              23  10000.0     1  15.99   351.53     3   2.0      1
 24              24   9000.0     1   8.24   283.03     2   2.0      3
 25              25  20000.0     1  15.99   703.05     3   1.0      3
 26              26   5000.0     1   7.49   155.51     1  10.0      2
 27              27  28000.0     2  18.99   726.19     4  10.0      2
 28              28   8325.0     1  10.49   270.55     2  10.0      2
 29              29  13000.0     1   7.24   402.84     1   8.0      3
 ...            ...      ...   ...    ...      ...   ...   ...    ...
 103404      103404  20000.0     2  15.59   482.02     3   7.0      2
 103405      103405  16000.0     2  13.99   372.21     3   3.0      3
 103406      103406  24750.0     2  10.49   531.86     2  10.0      2
 103407      103407  20000.0     2  15.59   482.02     3   9.0      2
 103408      103408  32000.0     2  13.99   744.42     3  10.0      2
 103409      103409  38000.0     2  13.49   874.18     3  10.0      2
 103410      103410  16000.0     2  10.99   347.80     2  10.0      2
 103411      103411  36000.0     2  10.99   782.55     2  10.0      1
 103412      103412  11200.0     2  13.49   257.66     3   5.0      3
 103413      103413  32000.0     2  14.49   752.74     3  10.0      2
 103414      103414  40000.0     2  15.59   964.03     3   1.0      2
 103415      103415  22000.0     2  13.99   511.79     3  10.0      3
 103416      103416  30000.0     2   9.49   629.91     2  10.0      2
 103417      103417  30000.0     2  13.99   697.90     3  10.0      3
 103418      103418  24000.0     2  12.79   543.50     3  10.0      3
 103419      103419  15000.0     1  10.49   487.47     2   8.0      2
 103420      103420  36400.0     2  14.49   856.24     3   5.0      3
 103421      103421  28000.0     2   8.99   581.10     2   2.0      2
 103422      103422  23800.0     2  14.49   559.85     3  10.0      2
 103423      103423  40000.0     2  10.49   859.56     2   5.0      2
 103424      103424  18000.0     2   9.49   377.95     2   5.0      1
 103425      103425  29400.0     2  13.99   683.94     3   9.0      2
 103426      103426  32000.0     2  14.49   752.74     3   3.0      2
 103427      103427  16000.0     2  12.79   362.34     3  10.0      3
 103428      103428  24000.0     2  10.49   515.74     2   4.0      1
 103429      103429  24000.0     2  12.79   543.50     3   7.0      2
 103430      103430  24000.0     2  10.49   515.74     2  10.0      2
 103431      103431  40000.0     2  10.49   859.56     2   9.0      2
 103432      103432  24000.0     2  14.49   564.56     3   6.0      3
 103433      103433  14000.0     2  14.49   329.33     3  10.0      2

              年收入  收入是否由LC验证  target                贷款目的   月负债比  \
 0        60000.0          3       0  debt_consolidation  30.76
 1       101800.0          3       0         credit_card  18.91
 2        75000.0          3       0               other  11.01
 3        60000.0          3       0         credit_card  18.91
 4        83807.4          1       0  debt_consolidation  13.17
 5        54000.0          2       0         credit_card  20.00
 6        60000.0          1       0         credit_card  16.49
 7        60000.0          2       0      small_business  20.06
 8       125000.0          3       0  debt_consolidation  20.18
 9        52000.0          1       0         credit_card  29.93
 10       78000.0          1       0  debt_consolidation  33.14
 11       57000.0          1       0         credit_card  28.45
 12       63000.0          3       0  debt_consolidation  29.03
 13       75000.0          3       0    home_improvement  16.98
 14      135000.0          3       0    home_improvement   6.60
 15       89712.0          3       0         credit_card  20.30
 16       85000.0          3       0  debt_consolidation  12.80
 17       32000.0          3       0         credit_card  29.93
 18      170000.0          3       0               other  16.24
 19       71000.0          3       0    home_improvement  32.94
 20       30000.0          3       0         credit_card   9.26
 21       62000.0          1       0  debt_consolidation  16.12
 22       78200.0          2       0  debt_consolidation  10.93
 23       40000.0          3       0  debt_consolidation  29.28
 24       65000.0          3       0         credit_card  18.56
 25      235000.0          1       0  debt_consolidation   5.46
 26       29000.0          2       0  debt_consolidation   6.66
 27      140000.0          2       0  debt_consolidation  24.12
 28       54000.0          3       0  debt_consolidation  20.29
 29       45000.0          3       0  debt_consolidation   2.40
 ...          ...        ...     ...                 ...    ...
 103404   91000.0          2       0             medical  23.24
 103405  153000.0          3       0  debt_consolidation  15.00
 103406   55000.0          2       0  debt_consolidation  26.71
 103407  177000.0          2       0    renewable_energy  12.36
 103408  125000.0          1       1  debt_consolidation  29.89
 103409  120000.0          1       0    home_improvement  14.44
 103410  120000.0          3       0  debt_consolidation  12.40
 103411  101000.0          1       0         credit_card  11.55
 103412   86000.0          1       0  debt_consolidation   4.80
 103413   98000.0          2       0  debt_consolidation   3.43
 103414  220000.0          2       0  debt_consolidation  10.88
 103415   93600.0          3       0  debt_consolidation  11.42
 103416  110000.0          2       0             medical  10.20
 103417  107000.0          2       0  debt_consolidation  28.38
 103418   63000.0          2       0  debt_consolidation  19.73
 103419   60000.0          3       0  debt_consolidation  26.40
 103420   95000.0          2       1         credit_card  21.50
 103421   97000.0          3       0  debt_consolidation  22.23
 103422  119000.0          3       0  debt_consolidation  32.73
 103423  150000.0          2       0  debt_consolidation  15.47
 103424  130000.0          3       0    home_improvement  20.59
 103425  180792.0          3       0  debt_consolidation  22.03
 103426  157000.0          1       1    home_improvement  10.34
 103427  150000.0          3       0             medical  12.25
 103428  125000.0          3       0         credit_card  10.98
 103429   95000.0          1       0    home_improvement  19.61
 103430  108000.0          3       0  debt_consolidation  34.94
 103431  227000.0          2       0  debt_consolidation  12.75
 103432  110000.0          3       1  debt_consolidation  18.30
 103433   95000.0          2       0  debt_consolidation  23.36

         过去两年借款人逾期30天以上的数字  过去6个月内被查询次数  摧毁公共记录的数量  额度循环使用率  总贷款笔数  拖欠的逾期款项  \
 0                     0.0            0        0.0     17.8   22.0      0.0
 1                     0.0            0        3.0     57.5   21.0      0.0
 2                     0.0            1        1.0     47.3    9.0      0.0
 3                     0.0            0        0.0     34.4   23.0      0.0
 4                     0.0            0        0.0     38.6   25.0      0.0
 5                     0.0            1        0.0     64.5   26.0      0.0
 6                     0.0            1        0.0     27.8   27.0      0.0
 7                     0.0            0        0.0     39.6   22.0      0.0
 8                     0.0            0        0.0     92.4   23.0      0.0
 9                     0.0            0        0.0     51.1   18.0      0.0
 10                    0.0            0        0.0     52.3   29.0      0.0
 11                    3.0            0        0.0     36.7   34.0      0.0
 12                    1.0            2        1.0     65.0   36.0      0.0
 13                    0.0            0        0.0     59.8   12.0      0.0
 14                    1.0            0        0.0     37.4   30.0      0.0
 15                    0.0            0        0.0     69.1   25.0      0.0
 16                    1.0            0        1.0     19.7   17.0      0.0
 17                    0.0            1        0.0     64.0   14.0      0.0
 18                    3.0            0        0.0     36.0   35.0      0.0
 19                    0.0            0        1.0     46.6   28.0      0.0
 20                    0.0            0        3.0     38.2    5.0      0.0
 21                    0.0            1        1.0     45.0   25.0      0.0
 22                    0.0            0        0.0     79.6   26.0      0.0
 23                    0.0            0        0.0     75.3   24.0      0.0
 24                    0.0            0        0.0     51.3   18.0      0.0
 25                    1.0            3        0.0     38.9   36.0      0.0
 26                    0.0            0        0.0     27.2   16.0      0.0
 27                    0.0            1        0.0     70.2   28.0      0.0
 28                    0.0            1        0.0     62.2   28.0      0.0
 29                    0.0            0        0.0     21.5   25.0      0.0
 ...                   ...          ...        ...      ...    ...      ...
 103404                2.0            1        1.0     54.4   32.0      0.0
 103405                1.0            0        1.0     56.5   32.0      0.0
 103406                1.0            0        0.0     64.0   11.0      0.0
 103407                0.0            0        5.0     60.8   20.0      0.0
 103408                1.0            2        0.0     41.6   38.0   2141.0
 103409                0.0            0        0.0     37.8   27.0      0.0
 103410                1.0            2        1.0      7.6   34.0      0.0
 103411                0.0            0        0.0     73.3   19.0      0.0
 103412                0.0            0        2.0     54.7   14.0      0.0
 103413                0.0            0        1.0     74.9   25.0      0.0
 103414                0.0            2        0.0     13.3   45.0      0.0
 103415                0.0            0        0.0     63.6   14.0      0.0
 103416                1.0            0        0.0     33.8   22.0      0.0
 103417                2.0            1        0.0     51.3   35.0      0.0
 103418                1.0            0        0.0     47.0   23.0      0.0
 103419                0.0            0        0.0     36.1   42.0      0.0
 103420                0.0            0        0.0     79.8   24.0      0.0
 103421                0.0            0        0.0     19.7   47.0      0.0
 103422                0.0            1        0.0     89.5   29.0      0.0
 103423                0.0            0        0.0     63.8   15.0      0.0
 103424                0.0            1        0.0     34.0   39.0      0.0
 103425                0.0            1        0.0     85.2   32.0      0.0
 103426                0.0            0        0.0     27.4   18.0      0.0
 103427                0.0            0        4.0     55.0   28.0      0.0
 103428                0.0            0        2.0     22.4   22.0      0.0
 103429                0.0            0        0.0     84.4   54.0      0.0
 103430                0.0            1        1.0     39.0   58.0      0.0
 103431                7.0            1        0.0     64.9   37.0      0.0
 103432                0.0            0        1.0     68.1   31.0      0.0
 103433                0.0            1        0.0     54.0   22.0      0.0

         留置税数量
 0         0.0
 1         0.0
 2         0.0
 3         0.0
 4         0.0
 5         0.0
 6         0.0
 7         0.0
 8         0.0
 9         0.0
 10        0.0
 11        0.0
 12        0.0
 13        0.0
 14        0.0
 15        0.0
 16        0.0
 17        0.0
 18        0.0
 19        0.0
 20        3.0
 21        0.0
 22        0.0
 23        0.0
 24        0.0
 25        0.0
 26        0.0
 27        0.0
 28        0.0
 29        0.0
 ...       ...
 103404    0.0
 103405    1.0
 103406    0.0
 103407    5.0
 103408    0.0
 103409    0.0
 103410    0.0
 103411    0.0
 103412    2.0
 103413    0.0
 103414    0.0
 103415    0.0
 103416    0.0
 103417    0.0
 103418    0.0
 103419    0.0
 103420    0.0
 103421    0.0
 103422    0.0
 103423    0.0
 103424    0.0
 103425    0.0
 103426    0.0
 103427    0.0
 103428    2.0
 103429    0.0
 103430    1.0
 103431    0.0
 103432    0.0
 103433    0.0

 [103434 rows x 20 columns]]

### （二）写

In [60]:
df_csv.to_html('.\\data_for_book\\chapter_06\\to_html.html')